package com.kecle.work.dao;

import com.kecle.work.pojo.LockAndManager;

public interface LockAndManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LockAndManager
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String lockid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LockAndManager
     *
     * @mbggenerated
     */
    int insert(LockAndManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LockAndManager
     *
     * @mbggenerated
     */
    int insertSelective(LockAndManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LockAndManager
     *
     * @mbggenerated
     */
    LockAndManager selectByPrimaryKey(String lockid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LockAndManager
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LockAndManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LockAndManager
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LockAndManager record);
    LockAndManager selectLockByLockId(String lockId);
}