package com.kecle.work.dao;

import com.kecle.work.pojo.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    User selectByNameAndPsw(@Param("ID")String user_id, @Param("password")String password);
    User checkDeviceId(@Param("ID") String ID);
    int writeDeviceID(@Param("ID")String usr_id, @Param("deviceId")String deviceId);
    List<User> searchBelongArea(@Param("belongArea")String belongArea);
    int insertNewUser(@Param("user_id")String user_id,@Param("password")String password);
    User checkUsername(@Param("user_id")String user_id);
}