package com.kecle.work.dao;

import com.kecle.work.pojo.UserAndLock;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserAndLockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserAndLock
     *
     * @mbggenerated
     */
    int insert(UserAndLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserAndLock
     *
     * @mbggenerated
     */
    int insertSelective(UserAndLock record);


    List<UserAndLock> selectByUserId(@Param("userId")String userId);
}