package com.kecle.work.pojo;

import java.util.Date;

public class LockAndManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LockAndManager.lockId
     *
     * @mbggenerated
     */
    private String lockid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LockAndManager.lockname
     *
     * @mbggenerated
     */
    private String lockname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LockAndManager.describe
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LockAndManager.byManager
     *
     * @mbggenerated
     */
    private String bymanager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LockAndManager.secretKey
     *
     * @mbggenerated
     */
    private String secretkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LockAndManager.lockState
     *
     * @mbggenerated
     */
    private Integer lockstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LockAndManager.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LockAndManager
     *
     * @mbggenerated
     */
    public LockAndManager(String lockid, String lockname, String describe, String bymanager, String secretkey, Integer lockstate, Date time) {
        this.lockid = lockid;
        this.lockname = lockname;
        this.describe = describe;
        this.bymanager = bymanager;
        this.secretkey = secretkey;
        this.lockstate = lockstate;
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LockAndManager
     *
     * @mbggenerated
     */
    public LockAndManager() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LockAndManager.lockId
     *
     * @return the value of LockAndManager.lockId
     *
     * @mbggenerated
     */
    public String getLockid() {
        return lockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LockAndManager.lockId
     *
     * @param lockid the value for LockAndManager.lockId
     *
     * @mbggenerated
     */
    public void setLockid(String lockid) {
        this.lockid = lockid == null ? null : lockid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LockAndManager.lockname
     *
     * @return the value of LockAndManager.lockname
     *
     * @mbggenerated
     */
    public String getLockname() {
        return lockname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LockAndManager.lockname
     *
     * @param lockname the value for LockAndManager.lockname
     *
     * @mbggenerated
     */
    public void setLockname(String lockname) {
        this.lockname = lockname == null ? null : lockname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LockAndManager.describe
     *
     * @return the value of LockAndManager.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LockAndManager.describe
     *
     * @param describe the value for LockAndManager.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LockAndManager.byManager
     *
     * @return the value of LockAndManager.byManager
     *
     * @mbggenerated
     */
    public String getBymanager() {
        return bymanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LockAndManager.byManager
     *
     * @param bymanager the value for LockAndManager.byManager
     *
     * @mbggenerated
     */
    public void setBymanager(String bymanager) {
        this.bymanager = bymanager == null ? null : bymanager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LockAndManager.secretKey
     *
     * @return the value of LockAndManager.secretKey
     *
     * @mbggenerated
     */
    public String getSecretkey() {
        return secretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LockAndManager.secretKey
     *
     * @param secretkey the value for LockAndManager.secretKey
     *
     * @mbggenerated
     */
    public void setSecretkey(String secretkey) {
        this.secretkey = secretkey == null ? null : secretkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LockAndManager.lockState
     *
     * @return the value of LockAndManager.lockState
     *
     * @mbggenerated
     */
    public Integer getLockstate() {
        return lockstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LockAndManager.lockState
     *
     * @param lockstate the value for LockAndManager.lockState
     *
     * @mbggenerated
     */
    public void setLockstate(Integer lockstate) {
        this.lockstate = lockstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LockAndManager.time
     *
     * @return the value of LockAndManager.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LockAndManager.time
     *
     * @param time the value for LockAndManager.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}