package com.kecle.work.pojo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.belongArea
     *
     * @mbggenerated
     */
    private String belongarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.bornArea
     *
     * @mbggenerated
     */
    private String bornarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.imageid
     *
     * @mbggenerated
     */
    private Integer imageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.autograph
     *
     * @mbggenerated
     */
    private String autograph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Ismanager
     *
     * @mbggenerated
     */
    private Integer ismanager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.deviceID
     *
     * @mbggenerated
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    public User(String id, String password, String username, String belongarea, String bornarea, Integer imageid, String sex, String autograph, Integer ismanager, String deviceid, Date time) {
        this.id = id;
        this.password = password;
        this.username = username;
        this.belongarea = belongarea;
        this.bornarea = bornarea;
        this.imageid = imageid;
        this.sex = sex;
        this.autograph = autograph;
        this.ismanager = ismanager;
        this.deviceid = deviceid;
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.ID
     *
     * @return the value of User.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.ID
     *
     * @param id the value for User.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.password
     *
     * @return the value of User.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.password
     *
     * @param password the value for User.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.username
     *
     * @return the value of User.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.username
     *
     * @param username the value for User.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.belongArea
     *
     * @return the value of User.belongArea
     *
     * @mbggenerated
     */
    public String getBelongarea() {
        return belongarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.belongArea
     *
     * @param belongarea the value for User.belongArea
     *
     * @mbggenerated
     */
    public void setBelongarea(String belongarea) {
        this.belongarea = belongarea == null ? null : belongarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.bornArea
     *
     * @return the value of User.bornArea
     *
     * @mbggenerated
     */
    public String getBornarea() {
        return bornarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.bornArea
     *
     * @param bornarea the value for User.bornArea
     *
     * @mbggenerated
     */
    public void setBornarea(String bornarea) {
        this.bornarea = bornarea == null ? null : bornarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.imageid
     *
     * @return the value of User.imageid
     *
     * @mbggenerated
     */
    public Integer getImageid() {
        return imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.imageid
     *
     * @param imageid the value for User.imageid
     *
     * @mbggenerated
     */
    public void setImageid(Integer imageid) {
        this.imageid = imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.sex
     *
     * @return the value of User.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.sex
     *
     * @param sex the value for User.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.autograph
     *
     * @return the value of User.autograph
     *
     * @mbggenerated
     */
    public String getAutograph() {
        return autograph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.autograph
     *
     * @param autograph the value for User.autograph
     *
     * @mbggenerated
     */
    public void setAutograph(String autograph) {
        this.autograph = autograph == null ? null : autograph.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Ismanager
     *
     * @return the value of User.Ismanager
     *
     * @mbggenerated
     */
    public Integer getIsmanager() {
        return ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Ismanager
     *
     * @param ismanager the value for User.Ismanager
     *
     * @mbggenerated
     */
    public void setIsmanager(Integer ismanager) {
        this.ismanager = ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.deviceID
     *
     * @return the value of User.deviceID
     *
     * @mbggenerated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.deviceID
     *
     * @param deviceid the value for User.deviceID
     *
     * @mbggenerated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.time
     *
     * @return the value of User.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.time
     *
     * @param time the value for User.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}